ILPSolverInterfaceImpl: Virtual methods are called do_xyz(), non-virtual methods xyz()
Exception: The virtual methods in the public interface ILPSolverInterface